accounts/urls.py
from django.urls import path
from .import views


app_name="accounts"

urlpatterns = [


    ###################  Website #######################
    # path('signup',views.signup,name="signup"),
    # path('home/',views.signup,name="signup"),
    path('loginpage/',views.loginpage,name="loginpage"),
    path('regpage/',views.regpage,name="regpage"),
    path('register/',views.register,name="register"),
    path('login_in/',views.login_in,name="login_in"),
   
   

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('lead/', include('lead.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('web.urls')),
    
    
    
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/urls.py
from django.urls import path
from .import views


app_name="web"

urlpatterns = [


    ###################  Website Pages#######################
    path('',views.webhome,name="webhome"),
    path('about',views.about,name="about"),
    path('services',views.services,name="services"),
    path('contact',views.contact,name="contact"),
    path('sentlead',views.sentlead,name="sentlead"),
    # path('get-topics-ajax/',views.get_topics_ajax, name="get_topics_ajax"),
    path('ajax/load-states/', views.load_states, name='ajax_load_states'),

  ###################  Web Contact Details #######################

    
    
    path('lead/view_webcontactdetails',views.view_webcontactdetails,name="view_webcontactdetails"),
    path('lead/add_webcontactdetails',views.add_webcontactdetails,name="add_webcontactdetails"),
    path('lead/create_webcontactdetails',views.create_webcontactdetails,name="create_webcontactdetails"),
    path('lead/edit_webcontactdetails/<int:id>',views.edit_webcontactdetails,name="edit_webcontactdetails"),
    path('lead/show_webcontactdetails/<int:id>',views.show_webcontactdetails,name="show_webcontactdetails"),
    path('lead/update_webcontactdetails<int:id>',views.update_webcontactdetails,name="update_webcontactdetails"),

]

lead/models.py
from datetime import timezone
from unicodedata import category
from django.db import models
from django.utils import timezone

# Create your models here.

def con_doc_path(instance, filename):
    return 'connector_documents/{0}/{1}'.format(instance.con_code, filename)

def banner_path(instance, filename):
    return 'webbanners/{0}/{1}'.format(instance.ban_code, filename)


class Category(models.Model): #country
    cat_id=models.CharField(max_length=100)
    name=models.CharField(max_length=100,unique=True)
    image=models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Service_types(models.Model): #city
    category=models.ForeignKey(Category, verbose_name="category", on_delete=models.CASCADE, related_name='services')
    name=models.CharField(max_length=100,unique=True)
    
    def __str__(self):
        return self.name

class Connector(models.Model):
    con_code=models.CharField(max_length=50,unique=True)
    con_name=models.CharField(max_length=50)
    con_mobile=models.DecimalField(max_digits=10,decimal_places=0)
    con_email=models.EmailField(max_length=254)
    con_document=models.FileField(upload_to =con_doc_path, default='connector_documents/default.jpg')
    con_account_no=models.DecimalField(max_digits=20,decimal_places=0)
    con_ifsc_code=models.CharField(max_length=50)
    con_bank_name=models.CharField(max_length=50)
    con_branch=models.CharField(max_length=50)
    con_reg_date=models.DateField(default=timezone.now)

    def __str__(self):
        return self.con_name
    
class Lead(models.Model):
    STATUS = [
    
    ('PENDING', 'PENDING'),
    ('APPROVED', 'APPROVED'),
    ('CLOSE', 'CLOSE'),
    ('CANCEL', 'CANCEL'),
    ]

    REVENUE_STATUS = [
    
    ('PENDING', 'PENDING'),
    ('PAID', 'PAID'),
    ('CANCEL', 'CANCEL'),
    ]
    lead_code=models.CharField(max_length=50,unique=True)
    lead_date=models.DateField(default=timezone.now)
    category=models.ForeignKey(Category,verbose_name="category",on_delete=models.CASCADE)
    service_type=models.ForeignKey(Service_types,verbose_name="services",on_delete=models.CASCADE)
    party_name=models.CharField(max_length=50,null=True, blank=True)  
    party_mobile=models.DecimalField(max_digits=10,decimal_places=0,null=True ,blank=True)
    party_email=models.EmailField(max_length=254,null=True, blank=True)
    party_address=models.CharField(max_length=100,null=True, blank=True)
    remark=models.CharField(max_length=250,null=True, blank=True)
    connector=models.ForeignKey(Connector,verbose_name="connector",on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS, default='PENDING', max_length=100,null=True, blank=True)
    con_paybal_revenue=models.DecimalField(max_digits=15,decimal_places=0,default=0,null=False)
    con_paid_revenue=models.DecimalField(max_digits=15,decimal_places=0,default=0,null=True, blank=True)
    trx_date=models.DateField(default=timezone.now)
    trx_no=models.CharField(max_length=254,default=0)
    con_revenue_status=models.CharField(choices=REVENUE_STATUS, default='PENDING', max_length=100,null=True, blank=True)
    
    def __str__(self):
        return self.party_name

class Banner(models.Model):
    ban_code=models.CharField(max_length=50,unique=True)
    ban_img=models.FileField(upload_to =banner_path, default='webbanners/default.jpg')
    ban_comments=models.CharField(max_length=50)
    ban_update_date=models.DateField(default=timezone.now)

    def __str__(self):
        return self.ban_comments

templates/website/about.html
{% extends 'website/webbase.html' %}

{% load static  %}
{% block content %}

        <div class="st-height-b80 st-height-lg-b80"></div>
        <!-- Start FunFact Aection -->
        <section class="st-dynamic-bg st-bg" data-src="{% static 'images/webimages/strip-banner.jpg'%}">
            <div class="st-height-b100 st-height-lg-b50"></div>
            <div class="container">
                <div class="st-cta st-style1 text-center">
                    <h2 class="st-cta-title">For the People, By the People. </h2>
                    <div class="st-cta-subtitle">If you want to earn a little on the side  all you have to do is give us the references of the people who need help and earn a <b>SECOND INCOME.</b>
                    </div>
                </div>
            </div>
            <div class="st-height-b30 st-height-lg-b50"></div>
        </section>
        <!-- End FunFact Aection -->

          <!-- Start About Seciton -->
          <section id="about" style="background-color: #d1c5df;">
            <div class="st-height-b50 st-height-lg-b80"></div>
            <div class="container">
                <div class="st-section-heading st-style1">
                    <h2 class="st-section-heading-title">Welcome to PRAGATI CAPITAL & SERVICES</h2>
                    <div class="st-section-heading-seperator left wow fadeInRight" data-wow-duration="1s"
                        data-wow-delay="0.2s"></div>
                    <div class="st-section-heading-subtitle"></div>
                </div>
                <div class="st-height-b40 st-height-lg-b40"></div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="st-vertical-middle">
                            <div class="st-vertical-middle-in">
                                <div class="st-text-block st-style1">
                                    <h3 class="st-text-block-subtitle">About us</h3>
                                    <div class="st-height-b10 st-height-lg-b10"></div>
                                    <h2 class="st-text-block-title">We are awesome team work for your business dream
                                    </h2>
                                    <div class="st-height-b20 st-height-lg-b20"></div>
                                    <div class="st-text-block-text"><p>Pragati Capitals and Services has been in the market for more than 10 years, providing 40+ services, 
                                        and are associated with more than 200+ vendors. We provide all kinds of services to help solve peoples' problems, 
                                        from loans to government work, you need help – think PRAGATI CAPITALS. </p>
                                        <p>Bring to the table win-win survival strategies to ensure proactive domination. At the end
                                            of the day, going forward, a new normal that has evolved from generation X is on the
                                            runway heading towards a streamlined cloud solution. User generated content in real-time
                                            will have multiple touchpoints for offshoring.</p>
                                    </div>  
                                            
                                </div>
                            </div>  
                        </div>
                        
                    </div><!-- .col -->
                    <div class="col-lg-6 wow fadeInRight" data-wow-duration="0.8s" data-wow-delay="0.2s">
                        <div class="st-hobble">
                            <div class="st-video-block st-style1 st-zoom st-hover-layer">
                                <div class="st-video-block-img st-zoom-in st-dynamic-bg"
                                    data-src="{% static 'images/webimages/about-us.jpg'%}"></div>
                            </div>
                        </div>
                        <!-- <div class="st-height-b30 st-height-lg-b30"></div> -->
                    </div><!-- .col -->
                </div>
            </div>
            <div class="st-height-b60 st-height-lg-b80"></div>
        </section>
       <!-- End About Seciton -->

       <div class="container">
        <div class="row mt-3">
          <div class="col-lg-6">
            <div class="st-iconbox st-style1">
              <div class="st-iconbox-icon"><i class="fa-solid fa-arrows-to-eye"></i></div>
              <h2 class="st-iconbox-title">Our Vison</h2>
              <div class="st-iconbox-text">Our vision is to provide a service platform <br>where people can seek help as well as haveanother means  ofearning through<br the reference> business model.A win-win situation for all. </div>
            </div>
            <div class="st-height-b30 st-height-lg-b30"></div>
          </div><!-- .col -->

          <div class="col-lg-6">
            <div class="st-iconbox st-style1">
              <div class="st-iconbox-icon"><i class="fa-solid fa-building-flag"></i></div>
              <h2 class="st-iconbox-title">Our Mission</h2>
              <div class="st-iconbox-text">Our mission is to provide a platform that<br> empowers the public by giving them an opportunity to earn a second income <br>making them self-sufficient. </div>
            </div>
            <div class="st-height-b30 st-height-lg-b30"></div>
          </div><!-- .col -->
        </div>
      </div>

    <!-- Start Skill Section -->
        <section class="logo-wm">
            <div class="st-height-b30 st-height-lg-b30"></div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="st-post-details st-style1">
                            
                            <div class="st-post-info">
                                <div class="st-post-text">
                                    <blockquote>“The sole reason we are in business is to make life less difficult for our clients”. – Unknown. 
                                    </blockquote>
                                    <div class="st-height-b30 st-height-lg-b30"></div>
                                    <p>We live by the quote, Pragati Capitals and Service's sole reason is to provide every possible solution for any problems faced by the people.
                                    
                                    With our diversified services and experts in the services we offer, we are sure to solve your problems. For us, customer satisfaction is our fuel to run this business. </p>
                                </div>
                                <div class="st-height-b35 st-height-lg-b35"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <hr>

       

    </div>





{%endblock%}

templates/website/contact.html
{% extends 'website/webbase.html' %}

{% load static  %}



{% block content %}

  <!-- End Header Section -->
  <div class="st-height-b110 st-height-lg-b20"></div>
  <div class="st-google-map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d96652.27317354927!2d-74.33557928194516!3d40.79756494697628!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c3a82f1352d0dd%3A0x81d4f72c4435aab5!2sTroy+Meadows+Wetlands!5e0!3m2!1sen!2sbd!4v1563075599994!5m2!1sen!2sbd" allowfullscreen></iframe>
  </div>
  <div class="st-content">
 
    <!-- Start Contact Section -->
    <section id="contact">
      <div class="st-height-b40 st-height-lg-b20"></div>
      <div class="container">
        <div class="st-section-heading st-style1">
          <h2 class="st-section-heading-title">Contact Us</h2>
          <div class="st-section-heading-seperator left wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.2s"></div>
          <div class="st-section-heading-subtitle">Need Help? Contact us and our team of experts will help you. </div>
        </div>
        <div class="st-height-b50 st-height-lg-b50"></div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
          <h5 style="color:green">{% if messages %}
            {% for message in messages %}
                <div>{{ message }}</div>
            {% endfor %}
        {% endif %}</h5>
            <div id="st-alert"> </div>
            <form action="{% url 'web:sentlead' %}" class="row st-contact-form" method="post"  id="contact-form">
              {% csrf_token %}
              


              <input  class="form-control" type="hidden" name="lead_code" value="{{ in_num }}" id="id_lead_code">
              <div class="col-lg-6">



                <div class="form-group">
                  <label for="categoryoptions">Category</label>
                  <select id="categoryoptions" class="form-control-sm custom-select" name="category">
                    <option>Select Category</option>
                    {% for category in category %}
                    <option value="{{category.pk}}">{{category.name}}</option>
                    {% endfor %}
                  </select>
                </div>

              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="serviceoptions">Services</label>
                  <select id="serviceoptions" class="form-control-sm custom-select" name="service_type">
                    <option >Select Service</option>
                    
                   
                  
                  </select>
                </div>
              
                {% comment %} <div class="form-group">
                    <label for="udepartment">Catagorys</label>
                    <select class="form-control" name="category" id="categories">
                      {% for i in category %}
                      <option value="{{i.pk}}"> {{i}}</option>
                      {%endfor%}
                     
                    </select>
                  </div>
               
              </div><!-- .col -->
              
              <div class="col-lg-6">
                <div class="form-group">
                  <label for="udepartment">Services</label>
                  <select class="form-control" name="service_type" id="services">
                   
                    {% for j in service%}
                    <option value="{{j.pk}}"> {{j}}</option>
                    {%endfor%}
                  </select>
                </div>  {% endcomment %}
             
            </div>
              <!-- .col -->
              <div class="col-lg-12">
                <div class="st-form-field">      
                  <input type="text" id="name" name="party_name" required>
                  <label>Full Name</label>
                </div>
              </div><!-- .col -->
              <div class="col-lg-6">
                <div class="st-form-field">      
                  <input type="text" id="email" name="party_email" required>
                  <label>Email Address</label>
                </div>
              </div><!-- .col -->
           
              <div class="col-lg-6">
                <div class="st-form-field">      
                  <input type="text" id="phone" name="party_mobile" required>
                  <label>Phone</label>
                </div>
              </div><!-- .col -->
              <div class="col-lg-12">
                <div class="st-form-field">      
                  <textarea cols="30" rows="10" id="msg" name="remark"required></textarea>
                  <label>Your Message</label>
                </div>
              </div>
              <div  class="form-group">
              
                <input type="hidden" value="{{request.user}}" id="phone" name="connector" required>
             
          {% comment %} <label for="id_connector">Connector</label>
            <select  class="form-control" name="connector"  id="id_connector" required >
              <option value="{{connect}}" selected></option>
              {% for i in connect%}
                <option value="{{i.id}}">
                    {{i}}
                </option>
                {% endfor %}
              </select>  {% endcomment %}
          </div><!-- .col -->
              <div class="col-lg-12">
                <button type="submit" value="Login" class="ast-smooth-move" style="background:#644ca9;color:#abc61d;waight:700">Submit</button>
                <div class="empty-space col-lg-b30"></div>
              </div><!-- .col -->
            </form>
            <div class="st-height-b30 st-height-lg-b30"></div>
          </div><!-- .col -->
          <div class="col-lg-4">
            <div class="st-contact-info">
              <h2 class="st-contact-info-title">Corporate Office</h2>
              <ul class="st-contact-info-list st-mp0">
                {% for i in webcontactdetails%}
                <li><i class="fas fa-map-marker-alt"></i>{{i.web_address}}</li>
                <li><i class="fas fa-phone-volume"></i><a href = "tel:{{i.web_contactno}}">+{{i.web_contactno}}</a></li>
                <li><i class="fas fa-envelope"></i><a href = "mailto: {{i.web_email}}">{{i.web_email}}</a></li>
                <li><i class="fas fa-globe"></i><a href="#">www.pragaticapitals.com</a></li>
              </ul>
             
            </div>
            <div class="st-height-b30 st-height-lg-b40"></div>
            <div class="st-shidule">
              <h2 class="st-shidule-title">Work Hours</h2>
              <ul class="st-shidule-list st-mp0">
                <li><span>Monday</span><span>{{i.web_worktime}}</span></li>
                <li><span>Tuesday</span><span>{{i.web_worktime}}</span></li>
                <li><span>Wednesday</span><span>{{i.web_worktime}}</span></li>
                <li><span>Thursday</span><span>{{i.web_worktime}}</span></li>
                <li><span>Friday</span><span>{{i.web_worktime}}</span></li>
                <li><span>Saturday</span><span>{{i.web_worktime}}</span></li>
                <li><span>Sunday</span><span>Closed</span></li>
              </ul>
            </div>
            <div class="st-height-b30 st-height-lg-b30"></div>
          </div>
        </div>
      </div>
      {% endfor %}
      <div class="st-height-b90 st-height-lg-b50"></div>
    </section>
    <!-- End Contact Section -->
    <hr>
    
  </div>

  {%endblock%}

  {% block script %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script>
   
  
 // category & services

 $("#categoryoptions").change(function () {
  var cate_id = $(this).val();
  
  $.ajax({
      url: "{% url 'web:ajax_load_states' %}",
      data: {
          'category': cate_id
      },
      success: function (data) {
          $("#serviceoptions").html(
              data);
      }
  });

});

  
  
  </script>
  {% endblock script %}




 

templates/website/webbase.html
{% load static  %}
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
  <!-- Meta Tags -->
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="">
  <!-- Page Title -->
  <title>Welcome to Pragati Capital & Services, Vadodara.</title>
  <!-- Favicon Icon -->
  <link rel="icon" href="{%static 'images/webimages/favicon.gif' %}" />
  <!-- Stylesheets -->
  <link rel="stylesheet" href="{%static 'assets/css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{%static 'assets/css/fontawesome.css' %}" />
  <link rel="stylesheet" href="{%static 'assets/css/flaticon.css' %}" />
  <link rel="stylesheet" href="{%static 'assets/css/slick.css' %}" />
  <link rel="stylesheet" href="{%static 'assets/css/lightgallery.min.css' %}" />
  <link rel="stylesheet" href="{%static 'assets/css/animate.css' %}" />
  <link rel="stylesheet" href="{%static 'assets/css/style.css' %}" />
  <script src="https://kit.fontawesome.com/be73d4c488.js"  crossorigin="anonymous"></script>
 <style>
  .active{

    background: #644ca9;
  }
 </style>

</head>

<body class="st-blue">
  <!-- Start Header Section -->
  <header class="st-site-header st-style1 st-sticky-header">
    <div class="st-top-header">
      {% comment %} {%for i in webcontactdetails %} {% endcomment %}
      <div class="container">
        {%for i in webcontactdetails %} 
        <div class="st-top-header-in">
     
          <ul class="st-top-header-list">

            <li><i class="fas fa-envelope"></i>Email: <a href="mailto:{{i.web_email}}">   {{i.web_email}}</a></li>
            <li><i class="fas fa-phone-volume"></i>Contact: <a href="tel:{{i.web_contactno}}">   {{i.web_contactno}}</a></li>
            <li><i class="fas fa-clock"></i>Work time: <a href="{% static '#' %}">   {{i.web_worktime}}</a></li>
          </ul>
      
        </div>
        {%endfor%} 
      </div>
  
    </div>
    <div class="st-main-header">
      <div class="container">
        <div class="st-main-header-in">
          <div class="st-main-header-left">
            <a class="st-site-branding st-white-logo" href="{% url 'web:webhome' %}"><img src="{% static 'images/webimages/logo-header.jpg'%}" alt="pcs-logo"></a>
            <a class="st-site-branding st-dark-logo" href="{% url 'web:webhome' %}"><img src="{% static 'images/webimages/logo-header.jpg'%}" alt="pcs-logo"></a>
          </div>
          <div class="st-main-header-right">
            <div class="st-nav">
              {% with request.resolver_match.url_name as url_name %}
              <ul class="st-nav-list st-onepage-nav">
                <li class="{% if url_name == 'webhome' %}active{% endif %}"><a href="{% url 'web:webhome' %}" class="st-smooth-move">Home</a></li>
                <li class="{% if url_name == 'about' %}active{% endif %}"><a href="{% url 'web:about' %}" class="st-smooth-move">About us</a></li>   
                <li class="{% if url_name == 'services' %}active{% endif %}"><a href="{% url 'web:services' %}" class="ast-smooth-move">Services</a></li>       
                <li class="{% if url_name == 'contact' %}active{% endif %}"><a href="{% url 'web:contact' %}" class="ast-smooth-move">Contact us</a></li>
                <li class="{% if url_name == 'login' %}active{% endif %}"><a href="{% url 'accounts:loginpage' %}" class="ast-smooth-move">Login</a></li>
              </ul>
              {% endwith %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- End Header Section -->

  <div class="st-content">
  


    {% block content %}







    {% endblock content %}

  </div>




 


  <!-- Start Footer -->
  <footer class="st-site-footer">
    <div class="st-main-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-3">
            <div class="st-footer-widget">
              <div class="st-text-field">
                <img src="{% static 'images/webimages/logo-footer.png'%}" alt="PCS" class="st-white-logo">
                <img src="{% static 'images/webimages/logo-footer.png'%}" alt="PCS" class="st-dark-logo">
                <div class="st-height-b25 st-height-lg-b25"></div>
                <div class="st-footer-text">We provide all kinds of services to help solve peoples' problems, from loans to government work, you need help – think PRAGATI CAPITALS.</div>
                <div class="st-height-b25 st-height-lg-b25"></div>
                <ul class="st-social-btn st-style1 st-mp0">
                  <li><a href="{% static '#'%}"><i class="fab fa-facebook-square"></i></a></li>
                  <li><a href="{% static '#'%}"><i class="fab fa-linkedin"></i></a></li>
                  <li><a href="{% static '#'%}"><i class="fab fa-pinterest-square"></i></a></li>
                </ul>
              </div>
            </div>
          </div><!-- .col -->
          <div class="col-lg-3">
            <div class="st-footer-widget">
              <h2 class="st-footer-widget-title">Our services</h2>
              <ul class="st-footer-widget-nav st-mp0">
                {% for i in cat %}
             
                <li><a href="{% url 'web:services'%}#{{i.cat_id}}"><i class="fas fa-chevron-right"></i> {{i.name}}</a></li>
               {%endfor%}
               
              </ul>
            </div>
          </div><!-- .col -->
          <div class="col-lg-3">
            <div class="st-footer-widget">
              <h2 class="st-footer-widget-title">Company Info</h2>
              <ul class="st-footer-widget-nav st-mp0">
                <li><a href="{% url 'web:about' %}" ><i class="fas fa-chevron-right"></i>About Us</a></li>
                <li><a href="{% url 'web:services' %}" ><i class="fas fa-chevron-right"></i>Our Services</a></li>
                <li><a href="{% url 'web:contact' %}"><i class="fas fa-chevron-right"></i>Contact</a></li>
              </ul>
            </div>
          </div><!-- .col -->
          <div class="col-lg-3">
            <div class="st-footer-widget">
              <h2 class="st-footer-widget-title">Useful Links</h2>
              <ul class="st-post-widget-list st-mp0">
                <li>
                  <div class="st-post st-style1">
                    <a href="{% static '#'%}" class="st-post-thumb st-zoom"><img src="{% static 'https://via.placeholder.com/80x70'%}" alt="post1" class="st-zoom-in"></a>
                    <div class="st-post-info">
                      <ul class="st-categories st-style1 st-mp0">
                        <li><a href="{% static '#'%}">Lifestyle</a></li>
                      </ul>
                      <h2 class="st-post-title"><a href="{% static 'blog-details.html'%}">Business Consultancy</a></h2>
                      <div class="st-post-date">1 Hours Ago</div>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="st-post st-style1">
                    <a href="{% static '#'%}" class="st-post-thumb st-zoom"><img src="{% static 'https://via.placeholder.com/80x70'%}" alt="post2" class="st-zoom-in"></a>
                    <div class="st-post-info">
                      <ul class="st-categories st-style1 st-mp0">
                        <li><a href="{% static '#'%}">Lifestyle</a></li>
                      </ul>
                      <h2 class="st-post-title"><a href="{% static 'blog-details.html'%}">Accessible New Design</a></h2>
                      <div class="st-post-date">3 Hours Ago</div>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div><!-- .col -->
        </div>
      </div>
    </div>
    <div class="st-copyright-wrap">
      <div class="container">
        <div class="st-copyright-in">
          <div class="st-left-copyright">
            <div class="st-copyright-text">Copyright  2022. Design by <a href="{% static 'https://www.prathasystech.in/'%}" target="_blank">PSPL</a> </div>
          </div>
          <div class="st-right-copyright">
            <div id="st-backtotop"><i class="fas fa-angle-up"></i></div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- End Footer -->
  <!-- Start Video Popup -->
  <div class="st-video-popup">
    <div class="st-video-popup-overlay"></div>
    <div class="st-video-popup-content">
      <div class="st-video-popup-layer"></div>
      <div class="st-video-popup-container">
        <div class="st-video-popup-align">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="about:blank"></iframe>
          </div>
        </div>
        <div class="st-video-popup-close"></div>
      </div>
    </div>
  </div>
  <!-- End Video Popup -->

  <!-- Scripts -->
  <script src="{% static 'assets/js/vendor/modernizr-3.5.0.min.js'%}"></script>
  <script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js'%}"></script>
  <script src="{% static 'assets/js/isotope.pkg.min.js'%}"></script>
  <script src="{% static 'assets/js/jquery.slick.min.js'%}"></script>
  <script src="{% static 'assets/js/mailchimp.min.js'%}"></script>
  <script src="{% static 'assets/js/counter.min.js'%}"></script>
  <script src="{% static 'assets/js/lightgallery.min.js'%}"></script>
  <script src="{% static 'assets/js/wow.min.js'%}"></script>
  <script src="{% static 'assets/js/textRotate.min.js'%}"></script>
  <script src="{% static 'assets/js/main.js'%}"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
{% block script%}

{%endblock script%}
</html>