accounts/urls.py
from django.urls import path
from .import views


app_name="accounts"

urlpatterns = [


    ###################  Website #######################
    # path('signup',views.signup,name="signup"),
    # path('home/',views.signup,name="signup"),
    path('loginpage/',views.loginpage,name="loginpage"),
    path('regpage/',views.regpage,name="regpage"),
    path('register/',views.register,name="register"),
    path('login_in/',views.login_in,name="login_in"),
   
   

]

lead/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views
app_name="lead"

urlpatterns = [


    ###################  Admin #######################
    path('home',views.home,name="home"),
    # path('lead/login',views.login,name="login"),
    # path('lead/registration',views.registration,name="registration"),
    path('lead/report',views.report,name="report"),

    ###################  Category #######################
    
    path('lead/view_cat',views.view_cat,name="view_cat"),
    path('lead/add_cat',views.add_cat,name="add_cat"),
    path('lead/create_cat',views.create_cat,name="create_cat"),
    path('lead/edit_cat/<int:id>',views.edit_cat,name="edit_cat"),
    path('lead/update_cat/<int:id>',views.update_cat,name="update_cat"),
    
    
    ###################  Services #######################

    path('lead/view_ser_type',views.view_ser_type,name="view_ser_type"),
    path('lead/add_ser_type',views.add_ser_type,name="add_ser_type"),
    path('lead/create_ser_type',views.create_ser_type,name="create_ser_type"),
    path('lead/edit_ser_type/<int:id>',views.edit_ser_type,name="edit_ser_type"),
    path('lead/update_ser_type/<int:id>',views.update_ser_type,name="update_ser_type"),

    ###################  Lead Details #######################
    path('lead/view_lead_reg',views.view_lead_reg,name="view_lead_reg"),
    path('lead/view_approved_lead_reg',views.view_approved_lead_reg,name="view_approved_lead_reg"),
    path('lead/view_pending_lead_reg',views.view_pending_lead_reg,name="view_pending_lead_reg"),
    path('lead/view_cancel_lead_reg',views.view_cancel_lead_reg,name="view_cancel_lead_reg"),
    path('lead/view_close_lead_reg',views.view_close_lead_reg,name="view_close_lead_reg"),
    path('lead/add_lead_reg',views.add_lead_reg,name="add_lead_reg"),
    path('lead/create_lead_reg',views.create_lead_reg,name="create_lead_reg"),
    path('lead/edit_lead_reg/<int:id>',views.edit_lead_reg,name="edit_lead_reg"),
    path('lead/update_lead_reg/<int:id>',views.update_lead_reg,name="update_lead_reg"),

    ###################  Connector Details #######################

    
    
    path('lead/view_con_reg',views.view_con_reg,name="view_con_reg"),
    path('lead/add_con_reg',views.add_con_reg,name="add_con_reg"),
    path('lead/create_con_reg',views.create_con_reg,name="create_con_reg"),
    path('lead/edit_con_reg/<int:id>',views.edit_con_reg,name="edit_con_reg"),
    path('lead/show_con_reg/<int:id>',views.show_con_reg,name="show_con_reg"),
    path('lead/update_con_reg<int:id>',views.update_con_reg,name="update_con_reg"),


    path('lead/view_reg',views.view_reg,name="view_reg"),


    ###################  Banner Details #######################

    
    
    path('lead/view_banner',views.view_banner,name="view_banner"),
    path('lead/add_banner',views.add_banner,name="add_banner"),
    path('lead/create_banner',views.create_banner,name="create_banner"),
    path('lead/edit_banner/<int:id>',views.edit_banner,name="edit_banner"),
    path('lead/show_banner/<int:id>',views.show_banner,name="show_banner"),
    path('lead/update_banner<int:id>',views.update_banner,name="update_banner"),

    ###################  Revenue #######################

    path('lead/view_revenue',views.view_revenue,name="view_revenue"),
   
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('lead/', include('lead.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('web.urls')),
    
    
    
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/urls.py
from django.urls import path
from .import views


app_name="web"

urlpatterns = [


    ###################  Website Pages#######################
    path('',views.webhome,name="webhome"),
    path('about',views.about,name="about"),
    path('services',views.services,name="services"),
    path('contact',views.contact,name="contact"),
    path('sentlead',views.sentlead,name="sentlead"),
    # path('get-topics-ajax/',views.get_topics_ajax, name="get_topics_ajax"),
    path('ajax/load-states/', views.load_states, name='ajax_load_states'),

  ###################  Web Contact Details #######################

    
    
    path('lead/view_webcontactdetails',views.view_webcontactdetails,name="view_webcontactdetails"),
    path('lead/add_webcontactdetails',views.add_webcontactdetails,name="add_webcontactdetails"),
    path('lead/create_webcontactdetails',views.create_webcontactdetails,name="create_webcontactdetails"),
    path('lead/edit_webcontactdetails/<int:id>',views.edit_webcontactdetails,name="edit_webcontactdetails"),
    path('lead/show_webcontactdetails/<int:id>',views.show_webcontactdetails,name="show_webcontactdetails"),
    path('lead/update_webcontactdetails<int:id>',views.update_webcontactdetails,name="update_webcontactdetails"),

]

lead/models.py
from datetime import timezone
from unicodedata import category
from django.db import models
from django.utils import timezone

# Create your models here.

def con_doc_path(instance, filename):
    return 'connector_documents/{0}/{1}'.format(instance.con_code, filename)

def banner_path(instance, filename):
    return 'webbanners/{0}/{1}'.format(instance.ban_code, filename)


class Category(models.Model): #country
    cat_id=models.CharField(max_length=100)
    name=models.CharField(max_length=100,unique=True)
    image=models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Service_types(models.Model): #city
    category=models.ForeignKey(Category, verbose_name="category", on_delete=models.CASCADE, related_name='services')
    name=models.CharField(max_length=100,unique=True)
    
    def __str__(self):
        return self.name

class Connector(models.Model):
    con_code=models.CharField(max_length=50,unique=True)
    con_name=models.CharField(max_length=50)
    con_mobile=models.DecimalField(max_digits=10,decimal_places=0)
    con_email=models.EmailField(max_length=254)
    con_document=models.FileField(upload_to =con_doc_path, default='connector_documents/default.jpg')
    con_account_no=models.DecimalField(max_digits=20,decimal_places=0)
    con_ifsc_code=models.CharField(max_length=50)
    con_bank_name=models.CharField(max_length=50)
    con_branch=models.CharField(max_length=50)
    con_reg_date=models.DateField(default=timezone.now)

    def __str__(self):
        return self.con_name
    
class Lead(models.Model):
    STATUS = [
    
    ('PENDING', 'PENDING'),
    ('APPROVED', 'APPROVED'),
    ('CLOSE', 'CLOSE'),
    ('CANCEL', 'CANCEL'),
    ]

    REVENUE_STATUS = [
    
    ('PENDING', 'PENDING'),
    ('PAID', 'PAID'),
    ('CANCEL', 'CANCEL'),
    ]
    lead_code=models.CharField(max_length=50,unique=True)
    lead_date=models.DateField(default=timezone.now)
    category=models.ForeignKey(Category,verbose_name="category",on_delete=models.CASCADE)
    service_type=models.ForeignKey(Service_types,verbose_name="services",on_delete=models.CASCADE)
    party_name=models.CharField(max_length=50,null=True, blank=True)  
    party_mobile=models.DecimalField(max_digits=10,decimal_places=0,null=True ,blank=True)
    party_email=models.EmailField(max_length=254,null=True, blank=True)
    party_address=models.CharField(max_length=100,null=True, blank=True)
    remark=models.CharField(max_length=250,null=True, blank=True)
    connector=models.ForeignKey(Connector,verbose_name="connector",on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS, default='PENDING', max_length=100,null=True, blank=True)
    con_paybal_revenue=models.DecimalField(max_digits=15,decimal_places=0,default=0,null=False)
    con_paid_revenue=models.DecimalField(max_digits=15,decimal_places=0,default=0,null=True, blank=True)
    trx_date=models.DateField(default=timezone.now)
    trx_no=models.CharField(max_length=254,default=0)
    con_revenue_status=models.CharField(choices=REVENUE_STATUS, default='PENDING', max_length=100,null=True, blank=True)
    
    def __str__(self):
        return self.party_name

class Banner(models.Model):
    ban_code=models.CharField(max_length=50,unique=True)
    ban_img=models.FileField(upload_to =banner_path, default='webbanners/default.jpg')
    ban_comments=models.CharField(max_length=50)
    ban_update_date=models.DateField(default=timezone.now)

    def __str__(self):
        return self.ban_comments

templates/add_webcontactdetails.html
{% extends 'base.html' %}

{% load static  %}
{% block content %}
{%load crispy_forms_filters%}



<div class="col-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Website Contact Details</h4>
      <p class="card-description">
        Add New contatc Details
      </p>
      <form class="forms-sample" action="{% url 'web:create_webcontactdetails' %}" method="post"  >
        {% csrf_token %}
       
        <div class="form-group">
          <label for="id_party_name">Email ID</label>
          <input type="email" class="form-control" name="web_email" id="id_party_name" autocomplete="off"  placeholder="Email ID" required>
        </div>
        <div class="form-group">
          <label for="id_party_mobile">Contact No</label>
          <input type="number" class="form-control" name="web_contactno" id="id_party_mobile" autocomplete="off"  placeholder="Contact No" required>
        </div>{% comment %} step="1"  {% endcomment %}
        <div class="form-group">
          <label for="id_party_email">Work Time</label>
          <input type="text" name="web_worktime" class="form-control" id="id_party_email" autocomplete="off"  maxlength="254" placeholder="Work Time " required >
        </div>
        <div class="form-group">
          <label for="id_party_address">Address</label>
          <textarea class="form-control" maxlength="100" name="web_address" autocomplete="off"  id="id_party_address" rows="4" required></textarea>
        </div>
        
        <button type="submit" class="btn btn-primary mr-2">Submit</button>
     <a href="{% url 'web:view_webcontactdetails' %}"  class="btn btn-light">Cancel</a>
      </form>
    </div>
  </div>
</div>
{%endblock%}

templates/edit_banner.html
{% extends 'base.html' %}

{% load static  %}
{% block content %}
{%load crispy_forms_filters%}






<div class="col-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Connector</h4>
      <p class="card-description">
        Edit Connector
      </p>
      <form class="forms-sample" action="{% url 'lead:update_banner' editbanner.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_ban_code">Banner Code</label>
          <input type="text" class="form-control" name="ban_code" value="{{ editbanner.ban_code }}" id="id_ban_code" readonly placeholder="Name">
        </div>
        
        <div class="form-group">
          <label>Image upload</label>
          {% if editbanner.ban_img %}
      <a href="/media/{{editbanner.ban_img}}" target="_blank">View Image</a>
      {% endif %}
          <input type="file" value="" name="ban_img" class="file-upload-default">
          <div class="input-group col-xs-12">
            <input type="text" class="form-control file-upload-info" autocomplete="off"  disabled placeholder="Upload File">
            <span class="input-group-append">
              <button class="file-upload-browse btn btn-primary" type="button">Upload</button>
            </span>
          </div>
        </div>
        
        <div class="form-group">
          <label for="id_con_bank_name">Banner Comments</label>
          <input type="text" name="ban_comments" autocomplete="off"  value="{{editbanner.ban_comments }}"  class="form-control" id="id_con_bank_name" placeholder="Bank Name">
        </div>
        
        
        <button type="submit" class="btn btn-primary mr-2">Submit</button>
        <a href="{% url 'lead:view_banner' %}"  class="btn btn-light">Cancel</a>
      </form>
    </div>
  </div>
</div>
{%endblock%}

templates/edit_cat.html
{% extends 'base.html' %}

{% load static  %}
{% block content %}
{%load crispy_forms_filters%}




<div class="col-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Category</h4>
        <p class="card-description">
          Update category
        </p>
        <form action="{% url 'lead:update_cat' editcat.pk %}" method="post" >
            {% csrf_token %}
          <div class="form-group">
            <label for="id_name">Name</label>
            <input type="text" class="form-control" autocomplete="off" name="name" value="{{editcat.name }}"   id="id_name" placeholder="Name">
          </div>
          
          <button type="submit" class="btn btn-primary mr-2">Submit</button>
          <a href="{% url 'lead:view_cat' %}"  class="btn btn-light">Cancel</a>
        </form>
      </div>
    </div>
  </div>

{%endblock%}

templates/edit_con_reg.html
{% extends 'base.html' %}

{% load static  %}
{% block content %}
{%load crispy_forms_filters%}






<div class="col-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Connector</h4>
      <p class="card-description">
        Edit Connector
      </p>
      <form class="forms-sample" action="{% url 'lead:update_con_reg' editconreg.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_con_code">Connector Code</label>
          <input type="text" class="form-control" name="con_code" value="{{ editconreg.con_code }}" id="id_con_code" readonly placeholder="Name">
        </div>
        <div class="form-group">
          <label for="id_con_name">Name</label>
          <input type="text" class="form-control" autocomplete="off"  name="con_name" value="{{editconreg.con_name }}" maxlength="50"  id="id_con_name" placeholder="Name">
        </div>
        <div class="form-group">
          <label for="id_con_mobile">Mobile</label>
          <input type="number" name="con_mobile" autocomplete="off"  value="{{editconreg.con_mobile }}"  class="form-control"  maxlength="50"  id="id_con_mobile" placeholder="Mobile">
        </div>
        <div class="form-group">
          <label for="id_con_email">Email address</label>
          <input type="email" name="con_email" autocomplete="off"  class="form-control" value="{{editconreg.con_email }}"  id="id_con_email" placeholder="Email">
        </div>
        <div class="form-group">
          <label>Documents upload</label>
          {% if editconreg.con_document %}
      <a href="/media/{{editconreg.con_document}}" target="_blank">View Documents</a>
      {% endif %}
          <input type="file" value="" name="con_document" class="file-upload-default">
          <div class="input-group col-xs-12">
            <input type="text" class="form-control file-upload-info" autocomplete="off"  disabled placeholder="Upload File">
            <span class="input-group-append">
              <button class="file-upload-browse btn btn-primary" type="button">Upload</button>
            </span>
          </div>
        </div>
        <div class="form-group">
          <label for="id_con_account_no">Bank Account No</label>
          <input type="number" name="con_account_no" autocomplete="off"  value="{{editconreg.con_account_no }}"  class="form-control" id="id_con_account_no" placeholder="Bank Account No">
        </div>
        <div class="form-group">
          <label for="id_con_bank_name">Bank Name</label>
          <input type="text" name="con_bank_name" autocomplete="off"  value="{{editconreg.con_bank_name }}"  class="form-control" id="id_con_bank_name" placeholder="Bank Name">
        </div>
        <div class="form-group">
          <label for="id_con_ifsc_code">IFSC Code</label>
          <input type="text" name="con_ifsc_code" autocomplete="off"  value="{{editconreg.con_ifsc_code }}" class="form-control" id="id_con_ifsc_code" placeholder="IFSC Code">
        </div>
        <div class="form-group">
          <label for="id_con_branch">Branch Name</label>
          <input type="text" name="con_branch" autocomplete="off"  value="{{editconreg.con_branch }}"  class="form-control" id="id_con_branch" placeholder="Branch Name">
        </div>
        
        <button type="submit" class="btn btn-primary mr-2">Submit</button>
        <a href="{% url 'lead:view_con_reg' %}"  class="btn btn-light">Cancel</a>
      </form>
    </div>
  </div>
</div>
{%endblock%}

templates/edit_ser_type.html
{% extends 'base.html' %}

{% load static  %}
{% block content %}
{%load crispy_forms_filters%}





<div class="col-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Service Types</h4>
        <p class="card-description">
          Add New Service
        </p>
        <form action="{% url 'lead:update_ser_type' editsertype.pk %}" method="post" >
            {% csrf_token %}
          
            <div class="form-group">
                <label for="id_category">Category</label>
                <input type="text" class="form-control" name="category" value="{{editsertype.category }}" readonly required id="id_category" placeholder="Name">
              </div>

            <div class="form-group">
                    <label for="id_name">Service Type</label>
                    <input type="text" class="form-control" name="name" autocomplete="off"  value="{{editsertype.name }}"  required id="id_name" placeholder="Name">
                  </div>
          
          <button type="submit" class="btn btn-primary mr-2">Submit</button>
          <a href="{% url 'lead:view_ser_type' %}"  class="btn btn-light">Cancel</a>
        </form>
      </div>
    </div>
  </div>

  {%endblock%}

templates/login.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">


    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Pragati</title>
        <!-- plugins:css -->
        <link rel="stylesheet" href="{% static  'vendors/feather/feather.css' %}">
        <link rel="stylesheet" href="{% static  'vendors/ti-icons/css/themify-icons.css' %}">
        <link rel="stylesheet" href="{% static  'vendors/css/vendor.bundle.base.css'%}" >
        <!-- endinject -->
        <!-- Plugin css for this page -->
        <link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css'%}">
        <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'js/select.dataTables.min.css'%}">
        <!-- End plugin css for this page -->
        <!-- inject:css -->
      <link rel="stylesheet" href="{% static 'css/vertical-layout-light/style.css'%}">
        <!-- endinject -->
      <link rel="shortcut icon" href="{% static  'images/favicon.png'%}" />
      </head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo">
                <a class="brand-logo " href="{% url 'web:webhome' %}"><h3 class="text-primary">PRAGATI</h3></a>
              </div>
              <h4>Hello! let's get started</h4>
              <h6 class="font-weight-light">Sign in to continue.</h6>
              <div>
               
                  {% for message in messages %}
                  <h4 style="color: red"> {{message}}  </h4>
                  {% endfor %}
              
        </div>
              <form class="pt-3" action="{% url 'accounts:login_in' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                <input type="text" class="form-control form-control-lg" name="username" placeholder="username">
                </div>
                <div class="form-group">
                <input type="password" class="form-control form-control-lg" name="password" placeholder="password">
                </div>
                <div class="mt-3">
                  <button type="submit" value="Login" class="btn btn-block btn-primary btn-lg font-weight-medium"><i class="ti-key   mr-2"></i>Login</button>
                </div>
                
                <div class="my-2 d-flex justify-content-between align-items-center">
                  <div class="form-check">
                    <label class="form-check-label text-muted">
                      <input type="checkbox" class="form-check-input">
                      Keep me signed in
                    </label>
                  </div>
                  <a href="#" class="auth-link text-black">Forgot password?</a>
                </div>
                {% comment %} <div class="mb-2">
                  
                  <a href="{% url 'accounts:regpage' %}"  class="btn btn-block btn-facebook auth-form-btn"> <i class="ti-user   mr-2"></i>New User Registration</a>
                </div> {% endcomment %}
                <div class="text-center mt-4 font-weight-light">
                  Don't have an account? <a href="{% url 'accounts:regpage' %}" class="text-primary">Create</a>
                </div>
            </form>
        
        
           
            </div>
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
  </div>
  <!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->
<!-- plugins:js -->
<footer class="footer">
    <div class="d-sm-flex justify-content-center">
        <p><span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2022 Developed by <a href="https://prathasystech.in/">PSPL.</a>
            All rights reserved.
          </p>
    </div>
    
    
  </footer> 
  <!-- partial -->
  <!-- plugins:js -->
  <script src="{%static  'vendors/js/vendor.bundle.base.js'%}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <script src="{%static  'vendors/chart.js/Chart.min.js'%}"></script>
  <script src="{%static  'vendors/datatables.net/jquery.dataTables.js'%}"></script>
  <script src="{%static  'vendors/datatables.net-bs4/dataTables.bootstrap4.js'%}"></script>
  <script src="{%static  'js/dataTables.select.min.js'%}"></script> 

  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="{%static  'js/off-canvas.js'%}"></script>
  <script src="{%static  'js/hoverable-collapse.js'%}"></script>
  <script src="{%static  'js/template.js'%}"></script>
  <script src="{%static  'js/settings.js'%}"></script>
  <script src="{%static  'js/todolist.js'%}"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{%static  'js/dashboard.js'%}"></script>
  <script src="{%static  'js/Chart.roundedBarCharts.js'%}"></script>
  <!-- End custom js for this page-->
</body>

</html>

templates/report.html
{% extends 'base.html' %}

{% load static  %}
{% block content %}
{%load crispy_forms_filters%}




<div class="col-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Reports</h4>
            <p class="card-description">
            reports
            </p>
            
          </div>
        </div>
      </div>

      {%endblock%}
                   
                

templates/show_webcontactdetails.html
{% extends 'base.html' %}

{% load static  %}
{% block content %}
{%load crispy_forms_filters%}


<div class="col-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Website Contact Details</h4>
      <p class="card-description">
        Show Website Contect Details
      </p>
      <form class="forms-sample" action="{% url 'web:view_webcontactdetails' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_ban_code">Email ID</label>
          <input type="email" class="form-control" name="web_email" value="{{ editwebcontactdetails.web_email }}" id="id_ban_code" readonly placeholder="Name">
        </div>
        
        <div class="form-group">
          <label for="id_con_branch">Contact No</label>
          <input type="number" name="web_contactno" value="{{editwebcontactdetails.web_contactno }}" readonly class="form-control" id="id_con_branch" placeholder="Branch Name">
        </div>

        <div class="form-group">
          <label for="id_con_branch">Address</label>
          <input type="text" name="web_address" value="{{editwebcontactdetails.web_address }}" readonly class="form-control" id="id_con_branch" placeholder="Branch Name">
        </div>

        <div class="form-group">
          <label for="id_con_branch">Work Time</label>
          <input type="text" name="web_worktime" value="{{editwebcontactdetails.web_worktime }}" readonly class="form-control" id="id_con_branch" placeholder="Branch Name">
        </div>
       
        <button type="submit" class="btn btn-primary mr-2">Submit</button>
        <button class="btn btn-light">Cancel</button>
      </form>
    </div>
  </div>
</div>
{%endblock%}

templates/view_banner.html
{% extends 'base.html' %}

{% load static  %}
{% block content %}



<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <div class="d-flex justify-content-between">
        <h4 class="card-title">Banner</h4>
        <a href="{% url 'lead:add_banner' %}">
        <button type="submit" class="btn btn-success">Add New Banner</button></a>
    </div>
    <p class="card-description">
        View Banner
       </p>
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Sr no</th>       
                <th>Banner Code</th>
                <th>Banner Comments</th>
                <th>Banner Image</th>
                <th></th>
                <th></th>
        
              </tr>
            
            </thead>
            <tbody>
              <tr>
                {% for i in view_banner%}
                <td>{{forloop.counter}}</td>
               
                <td>{{i.ban_code}}</td>
                <td>{{i.ban_comments}}</td>
                <td><a href="/media/{{i.ban_img}}" target="_blank">View Image</a></td>
                
                <td><a href="{% url 'lead:edit_banner' i.pk  %}">Edit Details</a></td>
                <td><a href="{% url 'lead:show_banner' i.pk  %}">Show Details</a></td>
                
               
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

templates/view_con_reg.html
{% extends 'base.html' %}

{% load static  %}
{% block content %}



<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <div class="d-flex justify-content-between">
        <h4 class="card-title">Connectors</h4>
        <a href="{% url 'lead:add_con_reg' %}">
        <button type="submit" class="btn btn-success">Add New Connector</button></a>
    </div>
    <p class="card-description">
        View Connectors
       </p>
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Sr no</th>       
                <th>Connector Code</th>
                <th>Name</th>
                <th>Mobile</th>
                <th>Email</th>
                <th>Document</th>
                <th></th>
                <th></th>
        
              </tr>
            
            </thead>
            <tbody>
              <tr>
                {% for i in view_con_reg%}
                <td>{{forloop.counter}}</td>
               
                <td>{{i.con_code}}</td>
                <td>{{i.con_name}}</td>
                <td>{{i.con_mobile}}</td>
                <td>{{i.con_email}}</td>
                <td><a href="/media/{{i.con_document}}" target="_blank">File</a></td>
                
                <td><a href="{% url 'lead:edit_con_reg' i.pk  %}">Edit Details</a></td>
                <td><a href="{% url 'lead:show_con_reg' i.pk  %}">Show Details</a></td>
                
               
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}